### ISSUE TITLE
No run-preprocess-acl2022.sh

### ISSUE THREAD

**Issue by SreehariSankar** [goodbai-nlp/AMR-Process#1]
File does not exist as cited in the AMRBART repo

**Comment by goodbai-nlp** [comment]
Hi, @SreehariSankar, thanks for pointing this out, please use  run-process-acl2022.sh.

**Comment by SreehariSankar** [comment]
Please specify how exactly to modify "inference-text.sh" to run on processed amr files; where to specify input, etc.. (run-process-acl22.sh worked)
